### ISSUE TITLE
How can I add to my project?

### ISSUE THREAD

**Issue by danieleabruzzi** [GvozdevLeonid/BackDrop-in-PyQt-PySide#2]

**Comment by danieleabruzzi** [comment]
I'm new in python world, but like a baby in a playground

**Comment by GvozdevLeonid** [comment]
Please take a look at the example file.
You need to download the Glassmorphism folder as well as the example file. After that, depending on the selected Qt shell, slightly change the example code.

**Comment by danieleabruzzi** [comment]
<img width="615" alt="image" src="https://github.com/GvozdevLeonid/BackDrop-in-PyQt-PySide/assets/76432082/6dad48a1-e207-411a-a96e-c53cfa3b3d16">

There's this problem
