### ISSUE TITLE
Questions about how widgets get pixmap which under them

### ISSUE THREAD

**Issue by MouseZhangZh** [GvozdevLeonid/BackDrop-in-PyQt-PySide#3]
Hi! I want rewrite the blur effect in C++/Qt, but I cannot get pixmap which under the widget.
Such as:
`base QWidget` contains 5 `icon QWidgets`, `icon QWidget` is transparent and have a blurred background, the blurred background's source is `base QWidget`.
I want to use **sourcePixmap** method get the background like:
```C++
void draw(QPainter* painter) override {
    ...
    QPixmap pixmap = sourcePixmap(Qt::DeviceCoordinates, &offset, QGraphicsEffect::PadToEffectiveBoundingRect);
    pixmap.save("capture.png");
    ...
}
```
But capture.png is always have nothing.
Could you please tell me how your code get the background? Hope for your replying!

**Comment by GvozdevLeonid** [comment]
Hello. I was getting the background image from the painter object during the draw function call. As I understand it, this object goes through the entire tree of nested objects and contains an image of the parent objects.

It is worth saying that you will not be able to get a background that is located outside the window (including the background under the window). I don't have time to implement this yet

let me know about your progress

**Comment by MouseZhangZh** [comment]
Thank you! I made a mistake, I should use the `QPainter* painter` to get background image, not `sourcePixmap`.
Just like this:
```C++
void draw(QPainter* painter) override {
    ...
    switch (painter->device()->devType()) {
    case QInternal::Image:
        QImage img = static_cast<QImage*>(painter->device())->copy(0, 0, 400, 400);
        img.save("capture.png");
    }
    ...
}
```
 I can get the image now, thank you again!
